USE [master]
GO
/****** Object:  Database [AspNetCoreToDo]    Script Date: 6/28/2017 13:24:25 ******/
CREATE DATABASE [AspNetCoreToDo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AspNetCoreToDo', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\AspNetCoreToDo.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AspNetCoreToDo_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\AspNetCoreToDo_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [AspNetCoreToDo] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AspNetCoreToDo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AspNetCoreToDo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET ARITHABORT OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AspNetCoreToDo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AspNetCoreToDo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AspNetCoreToDo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AspNetCoreToDo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AspNetCoreToDo] SET  MULTI_USER 
GO
ALTER DATABASE [AspNetCoreToDo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AspNetCoreToDo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AspNetCoreToDo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AspNetCoreToDo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [AspNetCoreToDo] SET DELAYED_DURABILITY = DISABLED 
GO
USE [AspNetCoreToDo]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 6/28/2017 13:24:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[Id] [int] NULL,
	[Name] [nvarchar](50) NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Tasks]    Script Date: 6/28/2017 13:24:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tasks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](500) NULL,
	[IsComplete] [bit] NULL,
	[CategoryId] [int] NULL
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [AspNetCoreToDo] SET  READ_WRITE 
GO